steps:
  - retriever:
      name: faiss
      model_name: paraphrase-multilingual-mpnet-base-v2
      top_k: 100
      cache: ./cache/vectors/multiclaim_extended/paraphrase-multilingual-mpnet-base-v2
      dataset:
        name: multiclaim_extended
        crosslingual: False
        fact_check_language: None
        language: None
        post_language: None
        split: None
        version: original
  - postprocessor:
      name: retriever_postprocessor